ldd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] +  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from main import forms
from main import views
from main import models

app_name = 'main'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='about_us.html'), name='about-us'),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('faq/', TemplateView.as_view(template_name='faq.html'), name='faq'),
    path('products/brand/<slug:brand>', views.ProductByBrandListView.as_view(), name='product-brand'),
    path('products/tags/<slug:tag>', views.ProductListView.as_view(), name='products'),
    path('product/<slug:slug>', DetailView.as_view(model=models.Product), name='product'),

    #Search
    #path('products/search/<slug:searchInput>', views.ProductSearchListView.as_view(), name='product-search'), """

    #Address CRUD
    path('address/', views.AddressListView.as_view(), name='address_list'),
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/<int:pk>/', views.AddressUpdateView.as_view(), name='address_update'),
    path('address/<int:pk>/delete/', views.AddressDeleteView.as_view(), name='address_delete'),

    # Authntication URLs
    path('accounts/register/', views.SignupView.as_view(), name='register'),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='main/auth/login.html', form_class=forms.AuthenticationForm), name='login'),
    path('accounts/logout/', LogoutView.as_view(), {'next_page': 'index'}, name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='main/auth/password_reset.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='main/auth/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='main/auth/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='main/auth/password_reset_complete.html'), name='password_reset_complete'),

    #basket
    path('add_to_basket', views.add_basket, name='add_to_basket'),
    path('basket/', views.manage_basket, name="basket"),
]

main/models.py
from django.contrib.auth.models import (AbstractUser, BaseUserManager,)
from django.urls import reverse
from django.db import models
from django.core.validators import MinValueValidator

class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class BrandManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class Brand(models.Model):
    name = models.CharField('nombre', max_length=20)
    slug = models.SlugField(max_length=20)
    active = models.BooleanField('activo',default=True)
    logo = models.ImageField(upload_to='logo-images', null=True)

    def __str__(self):
        return self.name
    
    def natural_key(self):
        return (self.slug,)

    objects = BrandManager()

    class Meta:
        verbose_name = 'Marca'

class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)
        
class ProductTag(models.Model):
    name = models.CharField('nombre', max_length=40)
    slug = models.SlugField(max_length=40)
    active = models.BooleanField('activo', default=True)

    def __str__(self):
        return self.name
   
    def natural_key(self):
        return (self.slug,)
   
    objects = ProductTagManager()

    class Meta:
        verbose_name = 'Etiqueta'

class ProductManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)

class Product(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name='marca')
    name = models.CharField('nombre', max_length=100)
    description = models.TextField('descripción', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    slug = models.SlugField(max_length=100)
    active = models.BooleanField('activo',default=True)
    in_stock = models.BooleanField('en stock', default=True)
    tags = models.ManyToManyField(ProductTag, blank=True)
    date_updated = models.DateTimeField('última actualización', auto_now=True)

    def get_image_url(self):
        try:
            return self.productimage_set.first().thumbnail.url
        except :
            return None
            
    class Meta:
        verbose_name = 'Producto'

    def __str__(self):
        return self.name
    
    def natural_key(self):
        return (self.slug,)

    slug_objects = ProductManager()
    objects = ActiveManager()

class ProductImageManager(models.Manager):
    def get_by_natural_key(self, image):
        return self.get(image=image)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='producto')
    image = models.ImageField('imagen', upload_to="product-images")
    thumbnail = models.ImageField('miniatura', upload_to="product-thumbnails", null=True)

    def __str__(self):
        return self.image.name.split('/')[-1]
    
    def natural_key(self):
        return (self.image,)
   
    objects = ProductImageManager()

    class Meta:
        verbose_name = 'Imagen'
        verbose_name_plural = 'Imagenes'


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, first_name, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, first_name, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, first_name, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField("email address", unique=True)
    first_name = models.CharField(max_length=40, blank=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ('AR', 'Argentina'),
        ('UY', 'Uruguay'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('nombre completo',max_length=60)
    address1 = models.CharField('dirección 1', max_length=120)
    phone = models.CharField('teléfono', max_length=20)
    zip_code = models.CharField('código postal', max_length=12)

    city = models.CharField('ciudad', max_length=50)
    country = models.CharField('país', max_length=3, choices=SUPPORTED_COUNTRIES)

    def get_absolute_url(self):
        return reverse("main:address_list")

    def __str__(self):
        return ", ".join(self.name, self.address1, self.phone, self.zip_code, self.city, self.country)

class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, 'Open'), (SUBMITTED, 'Submitted'))

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE, verbose_name='carrito')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='producto')
    quantity = models.PositiveIntegerField('cantidad', default=1, validators=[MinValueValidator(1)])
    
 

main/forms.py
from django.contrib.auth.forms import (UserCreationForm as DjangoUserCreationForm)
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import authenticate
from django.shortcuts import redirect
from django import forms
from django.forms import inlineformset_factory
from django.core.mail import send_mail
import logging
from main import models

logger = logging.getLogger(__name__)

CHOICES = [('M', 'Hombre'), ('F', 'Mujer')]
 
class ContactForm(forms.Form):
    name = forms.CharField(label=False, min_length=3, widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    subject = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'Asunto'}))
    email = forms.EmailField(label=False, widget=forms.EmailInput(attrs={'placeholder': 'Correo Electrónico'}))
    message = forms.CharField(label=False, widget=forms.Textarea(attrs={'placeholder': 'Escribe tu mensaje aquí'}))
    gender = forms.ChoiceField(required=False, widget=forms.RadioSelect, choices=CHOICES)

    def send_mail(self):
        logger.info('Sending email to customer service')
        message = f'From: {self.cleaned_data["name"]}\nemail: {self.cleaned_data["email"]}\nSubject: {self.cleaned_data["subject"]}\nMessage: {self.cleaned_data["message"]}'

        send_mail('Site Message', message, 'site@ldd.domain', ['customerservice@ldd.domain'], fail_silently=False)

class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ('email', 'first_name')
        field_classes = {'email': UsernameField}
    
    def send_mail(self):
        logger.info("Enviando correo de registro para email=%s", self.cleaned_data['email'],)
        message = f"Bienvenido {self.cleaned_data['email']}"
        send_mail('Bienvenido a LDD', message, 'site@ldd.com', [self.cleaned_data['email']], fail_silently=True)

class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user = authenticate(self.request, email=email, password=password)
            if self.user is None:
                raise forms.ValidationError("Usuario o contraseña incorrecta")
            logger.info("Authentication successful for email=%s", email)
    
        return self.cleaned_data

    def get_user(self):
        return self.user

BasketLineFormSet = inlineformset_factory(models.Basket, models.BasketLine, fields=('quantity',), extra=0,)

   

main/views.py
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
import logging
from django.contrib.auth import login, authenticate
from django.contrib import messages
from main import forms, models, views

logger = logging.getLogger(__name__)

class ContactView(FormView):
	template_name = 'contact.html'
	form_class = forms.ContactForm
	success_url = '/'

	def form_valid(self, form):
		form.send_mail()
		return super().form_valid(form)

class ProductListView(ListView):
	""" template_name = 'main/product_list.html' """
	""" context_object_name = 'product_list' """
	model = models.Product
	paginate_by = 20
   
	""" def get_context_data(self, **kwargs):
		context = super(ProductListView, self).get_context_data(**kwargs)
		context.update({'product_images_list': models.ProductImage.objects.all()})
		return context """
		
	def get_queryset(self):
		tag = self.kwargs['tag']
		self.tag = None
		if tag != 'all':
			self.tag = get_object_or_404(models.ProductTag, slug=tag)
		if self.tag:
			products = models.Product.objects.active().filter(tags=self.tag)
		else:
			products = models.Product.objects.active()
		
		return products.order_by('name')

class ProductByBrandListView(ListView):
	template_name = 'main/product_list.html'
	context_object_name = 'product_by_brand_list'
	model = models.Product
	paginate_by = 20

	def get_queryset(self):
		brand = self.kwargs['brand']
		self.brand = None
		if brand != 'all':
			self.brand = get_object_or_404(models.Brand, slug=brand)
		if self.brand:
			products = models.Product.objects.active().filter(brand=self.brand)
		else:
			products = models.Product.objects.active()
		
		return products.order_by('name')

""" class ProductSearchListView(ListView):
	template_name = 'main/product_list.html'
	context_object_name = 'product_search_list_list'
	model = models.Product
	paginate_by = 20

	def get_queryset(self):
		searchInput = self.kwargs['searchInput']
		self.searchInput = None
		if self.searchInput:
			if request.user.is_staff or request.user.is_supersuser:
				products = model.objects.filter(name=self.searchInput)
			products = models.objects.active().filter(name=self.searchInput)

		return products.order_by('name') """

class SignupView(FormView):
	template_name = 'main/auth/register.html'
	form_class = forms.UserCreationForm

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return redirect('/')
		return super().dispatch(request, *args, **kwargs)

	def get_success_url(self):
		redirect_to = self.request.GET.get('next', '/')
		return redirect_to
	
	def form_valid(self, form):
		response = super().form_valid(form)
		form.save()
		email = form.cleaned_data.get('email')
		first_name = form.cleaned_data.get('first_name')
		raw_password = form.cleaned_data.get('password1')
		logger.info('Nuevo registro para email=%s a través de SignupView', email)
		user = authenticate(email=email, password=raw_password)
		login(self.request, user)
		form.send_mail()

		return response

class AddressListView(LoginRequiredMixin, ListView):
	model = models.Address

	def get_queryset(self):
		return self.model.objects.filter(user=self.request.user)

class AddressCreateView(LoginRequiredMixin,CreateView):
	model = models.Address

	fields = ['name', 'address1', 'phone', 'zip_code', 'city', 'country']

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.user = self.request.user
		obj.save()
		return super().form_valid(form)

class AddressUpdateView(LoginRequiredMixin,UpdateView):
	model = models.Address

	fields = ['name', 'address1', 'phone', 'zip_code', 'city', 'country']

	success_url = reverse_lazy('main:address_list')

	def get_queryset(self):
		return self.model.objects.filter(user=self.request.user)

class AddressDeleteView(LoginRequiredMixin,DeleteView):
	model = models.Address
	success_url = reverse_lazy('main:address_list')

	def get_queryset(self):
		return self.model.objects.filter(user=self.request.user)

def add_basket(request):
	product = get_object_or_404(models.Product, pk=request.GET.get('product_id'))

	basket = request.basket
	if not request.basket:
		if request.user.is_authenticated:
			user = request.user
		else:
			user = None
		basket = models.Basket.objects.create(user=user)
		request.session['basket_id'] = basket.id
	
	basketline, created = models.BasketLine.objects.get_or_create(basket=basket, product=product)

	if not created:
		basketline.quantity += 1
		basketline.save()
	
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def manage_basket(request):
	if not request.basket:
		return render(request, 'basket.html', {'formset': None})

	if request.method == 'POST':
		formset = forms.BasketLineFormSet(request.POST, instance=request.basket)
		if formset.is_valid():
			formset.save()
	
	else:
		formset = forms.BasketLineFormSet(instance=request.basket)
	
	if request.basket.is_empty():
		return render(request, 'basket.html', {'formset': None})

	return render(request, 'basket.html', {'formset': formset})
	





	


		
	

main/templates/main/address_form.html
{% extends 'base.html' %}

{% block content %}

<main class="login-page">
        <div class="contact signin">
            <div class="titulos">
                    <p>Dirección</p>
            </div>

            <form method="POST" enctype="multipart/form-data" id="reg-form" novalidate>
                {% csrf_token %}
                <div class="input-group input-group-icon">
                    <input type="text" name="name" required value="{{ form.name.value|default:"" }}" placeholder="Nombre Completo" />
                    <div class="input-icon">
                        <i class="fas fa-user"></i>
                    </div>
                        {% if form.name.errors %}
                            <span class="obligatorio" >{{form.name.errors}}</span>
                        {% endif %}
                </div>

                <div class="input-group input-group-icon">
                    <input type="text" name="address1" required value="{{ form.address1.value|default:"" }}" placeholder="Dirección" />
                    <div class="input-icon">
                        <i class="fas fa-map-marker-alt"></i>
                    </div>
                        {% if form.address1.errors %}
                            <span class="obligatorio" >{{form.address1.errors}}</span>
                        {% endif %}
                </div>

                <div class="input-group input-group-icon">
                    <input type="text" name="phone" required value="{{ form.phone.value|default:"" }}" placeholder="Teléfono" />
                    <div class="input-icon">
                        <i class="fas fa-phone"></i>
                    </div>
                        {% if form.phone.errors %}
                            <span class="obligatorio" >{{form.phone.errors}}</span>
                        {% endif %}
                </div>

                <div class="input-group input-group-icon">
                    <input type="text" name="zip_code" required value="{{ form.zip_code.value|default:"" }}" placeholder="Código Postal" />
                    <div class="input-icon">
                        <i class="fas fa-mail-bulk"></i>
                    </div>
                        {% if form.zip_code.errors %}
                            <span class="obligatorio" >{{form.zip_code.errors}}</span>
                        {% endif %}
                </div>

                <div class="input-group input-group-icon">
                    <input type="text" name="city" required value="{{ form.city.value|default:"" }}" placeholder="Ciudad" />
                    <div class="input-icon">
                        <i class="fas fa-city"></i>
                    </div>
                        {% if form.city.errors %}
                            <span class="obligatorio" >{{form.city.errors}}</span>
                        {% endif %}
                </div>

                <div class="input-group input-group-icon">
                    <select name="country" required="" id="id_country">
                        <option value="" selected="{{ form.country_display.value}}">País</option>
                        <option value="AR">Argentina</option>
                        <option value="UY">Uruguay</option>
                    </select>
                    <div class="input-icon">
                        <i class="fas fa-flag"></i>
                    </div>
                    {% if form.country.errors %}
                            <span class="obligatorio" >{{form.country.errors}}</span>
                        {% endif %}
                </div>

                <div class="input-group">
                    <input type="submit" value="Enviar"/> 
                </div>
            </form>                               
        </div>
    </main>

{% endblock content %}

main/templates/main/address_list.html
{% extends 'base.html' %}

{% block content %}

<main class="login-page">
    <div class="contact signin address-list" id="book-table">
        <div class="titulos">
            <p>Domicilios</p>

            <button class="btn btn-secondary" type="button">
                <a href="{% url "main:address_create" %}">Agregar</a>
            </button>
        </div>   
        {% for address in object_list %}
        <div class="crud"> 
            <div>
                <p class="details">{{ address.name }}</p>
                <p class="details">{{ address.address1 }} ({{ address.zip_code }})</p>
                <p class="details">{{ address.phone }}</p>
                <p class="details">{{ address.city }}</p>
                <p class="details">{{ address.get_country_display}}</p>    
            </div>

            <div>
                <button class="btn btn-info" type="button">
                    <a href="{% url "main:address_update" address.id %}"><i class="fas fa-pen"></i></a>
                </button>

                <button class="btn btn-danger" type="button">
                    <a href="{% url "main:address_delete" address.id %}" class="confirm-delete" js-address="{{address.address1}}" data-toggle="modal" data-target="#confirmDeleteModal" id="{{address.id}}"><i class="fas fa-trash-alt"></i>
                    </a>
                </button>

                <div class="modal fade" id="confirmDeleteModal" tabindex="-1" caller-id="" caller-address="" role="dialog" 
                aria-labelledby="confirmDeleteModal" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-body confirm-delete" style="font-size: 0.85em">
                                {% comment %} El texto se completa con jQuery {% endcomment %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" caller-id="" data-dismiss="modal" data-target="modal">Cancelar</button>
                                <form  method="POST" action="{% url "main:address_delete" address.id %}" id="deleteForm">
                                        {% csrf_token %}
                                    <button type="submit" class="btn btn-danger" id="confirmDeleteButtonModal">Eliminar</a>
                                </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if not forloop.last %}<hr style="display: block">{% endif %}
        {% endfor %}
    </div>
</main>

{% endblock content %}

main/templates/main/product_detail.html
{% extends "base.html" %}
{% load humanize %}


{% block content %}
  <h1>Producto</h1>
  <table class="table">
    <tr>
      <th>Nombre</th>
      <td>{{ object.name }}</td>
    </tr>
    <tr>
      <th>Imágenes</th>
      <td>
        {% for image in object.productimage_set.all %}
        <img src ="{{ image.thumbnail.url }}" alt="cover" >     
        {% endfor %} 
      </td>
    </tr>
    <tr>
      <th>Precio</th>
      <td>$ {{ object.price|intcomma }}</td>
    </tr>
    <tr>
      <th>Descripción</th>
      <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
      <th>Etiquetas</th>
      <td>{{ object.tags.all|join:", "|default:"No tags available" }}</td>
    </tr>
    <tr>
      <th>En stock</th>
      <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
      <th>Actualizado</th>
      <td>{{ object.date_updated|date:"F Y" }}</td>
      
    </tr>
  </table>
  {% comment %} <a href="{% url "add_to_basket" %}?product_id={{ object.id }}">Add to basket</a> {% endcomment %}
{% endblock content %}

main/templates/main/product_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% comment %} {% load product_extras %} {% endcomment %}

{% block content %}
 
<div class="destacados">

    {% comment %} {% for product, image in products_list|zip:product_images_list %} no hace falta el nested{% endcomment %}
    {% for product in product_list %}
    <div class="collections coll-watches">
        <a href="{% url 'main:product' product.slug %}">
        {% if product.get_image_url%}
            <img class="foto" src="{{ product.get_image_url }}">   
        {% else %}
            <img class="foto" src="{% static 'images/image-not-found.png' %}"> 
        {% endif %}
        </a>
        <p class="prod-description">{{ product.name }}</p>
        <p class="prod-description prices"><strong>$ {{ product.price|intcomma }}</strong></p>
        <a class="boton-tr boton-tr-watches" href="{% url "main:add_to_basket" %}?product_id={{ product.id }}">Agregar al carrito</a>
    </div>
    {% endfor %}

    {% for product in product_by_brand_list %}
    <div class="collections coll-watches">
        <a href="{% url 'main:product' product.slug %}">
        {% if product.get_image_url%}
            <img class="foto" src="{{ product.get_image_url }}">           
        {% else %}
            <img class="foto" src="{% static 'images/image-not-found.png' %}">
        {% endif %}
        </a>
        <p class="prod-description">{{ product.name }}</p>
        <p class="prod-description prices"><strong>$ {{ product.price|intcomma }}</strong></p>
        <a class="boton-tr boton-tr-watches" href="{% url "main:add_to_basket" %}?product_id={{ product.id }}">Agregar al carrito</a>
    </div>

    {% endfor %}
</div>

{% comment %} {% for product in product_search_list %}
    <div class="collections coll-watches">
        <a href="{% url 'main:product' product.slug %}">
        {% if product.get_image_url%}
            <img class="foto" src="{{ product.get_image_url }}">           
        {% else %}
            <img class="foto" src="{% static 'images/image-not-found.png' %}">
        {% endif %}
        </a>
        <p class="prod-description">{{ product.name }}</p>
        <p class="prod-description prices"><strong>$ {{ product.price|intcomma }}</strong></p>
        <a class="boton-tr boton-tr-watches" href="#">Agregar al carrito</a>
    </div>
    {% endfor %} {% endcomment %}
</div>

<nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{page_obj.previous_page_number}}">Anterior</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Anterior</a>
        </li>
      {% endif %}
      {% for pagenum in page_obj.paginator.page_range %}
        <li
          class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
          <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Siguiente</a>
        </li>
      {% endif %}
    </ul>
  </nav>

{% endblock content %}

main/templates/main/reset_password_done.html
{% extends 'base.html' %}

{% block content %}

<main class="login-page">
    <div class="contact login">
        <div class="titulos">
            <p>Envío exitoso</p>
        </div>

        <form method="post" id="login" novalidate>
            {% csrf_token %}
            <div id="email" class="input-group input-group-icon">
                <input id="mail" type="email" name="email" placeholder="Correo electrónico" value="{{ form.email.value|default:"" }}"/>
                <div class="input-icon">
                    <i class="fas fa-envelope"></i>
                </div>
                <i id="mandatory" class="obligatorio"></i>
                {% if form.email.errors %}
                    <span class="obligatorio" >{{form.email.errors}}</span>
                {% endif %}
            </div>

            <div class="input-group">
                <input type="submit" value="Enviar" />
            </div>
            <label><b>Ingrese su correo electrónico y enviaremos las instrucciones para recuperar su contraseña</b></label>
        </form>
    </div>
</main>

{% endblock content %}