ldd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] +  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from main import forms
from main import views
from main import models

app_name = 'main'

urlpatterns = [
    path('about/', TemplateView.as_view(template_name='about_us.html'), name='about-us'),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('faq/', TemplateView.as_view(template_name='faq.html'), name='faq'),
    path('products/brand/<slug:brand>', views.ProductByBrandListView.as_view(), name='product-brand'),
    path('products/tags/<slug:tag>', views.ProductListView.as_view(), name='products'),
    path('product/<slug:slug>', DetailView.as_view(model=models.Product), name='product'),

    #Search
    #path('products/search/<slug:searchInput>', views.ProductSearchListView.as_view(), name='product-search'), """

    #Address CRUD
    path('address/', views.AddressListView.as_view(), name='address_list'),
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
    path('address/<int:pk>/', views.AddressUpdateView.as_view(), name='address_update'),
    path('address/<int:pk>/delete/', views.AddressDeleteView.as_view(), name='address_delete'),

    # Authntication URLs
    path('accounts/register/', views.SignupView.as_view(), name='register'),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='main/auth/login.html', form_class=forms.AuthenticationForm), name='login'),
    path('accounts/logout/', LogoutView.as_view(), {'next_page': 'index'}, name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='main/auth/password_reset.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='main/auth/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='main/auth/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='main/auth/password_reset_complete.html'), name='password_reset_complete'),

    #basket
    path('add_to_basket', views.add_basket, name='add_to_basket'),
    path('basket/', views.manage_basket, name="basket"),
]

main/models.py
from django.contrib.auth.models import (AbstractUser, BaseUserManager,)
from django.urls import reverse
from django.db import models
from django.core.validators import MinValueValidator

class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class BrandManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class Brand(models.Model):
    name = models.CharField('nombre', max_length=20)
    slug = models.SlugField(max_length=20)
    active = models.BooleanField('activo',default=True)
    logo = models.ImageField(upload_to='logo-images', null=True)

    def __str__(self):
        return self.name
    
    def natural_key(self):
        return (self.slug,)

    objects = BrandManager()

    class Meta:
        verbose_name = 'Marca'

class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)
        
class ProductTag(models.Model):
    name = models.CharField('nombre', max_length=40)
    slug = models.SlugField(max_length=40)
    active = models.BooleanField('activo', default=True)

    def __str__(self):
        return self.name
   
    def natural_key(self):
        return (self.slug,)
   
    objects = ProductTagManager()

    class Meta:
        verbose_name = 'Etiqueta'

class ProductManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)

class Product(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name='marca')
    name = models.CharField('nombre', max_length=100)
    description = models.TextField('descripción', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    slug = models.SlugField(max_length=100)
    active = models.BooleanField('activo',default=True)
    in_stock = models.BooleanField('en stock', default=True)
    tags = models.ManyToManyField(ProductTag, blank=True)
    date_updated = models.DateTimeField('última actualización', auto_now=True)

    def get_image_url(self):
        try:
            return self.productimage_set.first().thumbnail.url
        except :
            return None
            
    class Meta:
        verbose_name = 'Producto'

    def __str__(self):
        return self.name
    
    def natural_key(self):
        return (self.slug,)

    slug_objects = ProductManager()
    objects = ActiveManager()

class ProductImageManager(models.Manager):
    def get_by_natural_key(self, image):
        return self.get(image=image)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='producto')
    image = models.ImageField('imagen', upload_to="product-images")
    thumbnail = models.ImageField('miniatura', upload_to="product-thumbnails", null=True)

    def __str__(self):
        return self.image.name.split('/')[-1]
    
    def natural_key(self):
        return (self.image,)
   
    objects = ProductImageManager()

    class Meta:
        verbose_name = 'Imagen'
        verbose_name_plural = 'Imagenes'


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, first_name, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, first_name, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, first_name, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField("email address", unique=True)
    first_name = models.CharField(max_length=40, blank=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ('AR', 'Argentina'),
        ('UY', 'Uruguay'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('nombre completo',max_length=60)
    address1 = models.CharField('dirección 1', max_length=120)
    phone = models.CharField('teléfono', max_length=20)
    zip_code = models.CharField('código postal', max_length=12)

    city = models.CharField('ciudad', max_length=50)
    country = models.CharField('país', max_length=3, choices=SUPPORTED_COUNTRIES)

    def get_absolute_url(self):
        return reverse("main:address_list")

    def __str__(self):
        return ", ".join(self.name, self.address1, self.phone, self.zip_code, self.city, self.country)

class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, 'Open'), (SUBMITTED, 'Submitted'))

    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

class BasketLine(models.Model):
    basket = models.ForeignKey(Basket, on_delete=models.CASCADE, verbose_name='carrito')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='producto')
    quantity = models.PositiveIntegerField('cantidad', default=1, validators=[MinValueValidator(1)])
    
 

main/forms.py
from django.contrib.auth.forms import (UserCreationForm as DjangoUserCreationForm)
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import authenticate
from django.shortcuts import redirect
from django import forms
from django.forms import inlineformset_factory
from django.core.mail import send_mail
import logging
from main import models

logger = logging.getLogger(__name__)

CHOICES = [('M', 'Hombre'), ('F', 'Mujer')]
 
class ContactForm(forms.Form):
    name = forms.CharField(label=False, min_length=3, widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    subject = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'Asunto'}))
    email = forms.EmailField(label=False, widget=forms.EmailInput(attrs={'placeholder': 'Correo Electrónico'}))
    message = forms.CharField(label=False, widget=forms.Textarea(attrs={'placeholder': 'Escribe tu mensaje aquí'}))
    gender = forms.ChoiceField(required=False, widget=forms.RadioSelect, choices=CHOICES)

    def send_mail(self):
        logger.info('Sending email to customer service')
        message = f'From: {self.cleaned_data["name"]}\nemail: {self.cleaned_data["email"]}\nSubject: {self.cleaned_data["subject"]}\nMessage: {self.cleaned_data["message"]}'

        send_mail('Site Message', message, 'site@ldd.domain', ['customerservice@ldd.domain'], fail_silently=False)

class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ('email', 'first_name')
        field_classes = {'email': UsernameField}
    
    def send_mail(self):
        logger.info("Enviando correo de registro para email=%s", self.cleaned_data['email'],)
        message = f"Bienvenido {self.cleaned_data['email']}"
        send_mail('Bienvenido a LDD', message, 'site@ldd.com', [self.cleaned_data['email']], fail_silently=True)

class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user = authenticate(self.request, email=email, password=password)
            if self.user is None:
                raise forms.ValidationError("Usuario o contraseña incorrecta")
            logger.info("Authentication successful for email=%s", email)
    
        return self.cleaned_data

    def get_user(self):
        return self.user

BasketLineFormSet = inlineformset_factory(models.Basket, models.BasketLine, fields=('quantity',), extra=0,)

   

main/views.py
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
import logging
from django.contrib.auth import login, authenticate
from django.contrib import messages
from main import forms, models, views

logger = logging.getLogger(__name__)

class ContactView(FormView):
	template_name = 'contact.html'
	form_class = forms.ContactForm
	success_url = '/'

	def form_valid(self, form):
		form.send_mail()
		return super().form_valid(form)

class ProductListView(ListView):
	""" template_name = 'main/product_list.html' """
	""" context_object_name = 'product_list' """
	model = models.Product
	paginate_by = 20
   
	""" def get_context_data(self, **kwargs):
		context = super(ProductListView, self).get_context_data(**kwargs)
		context.update({'product_images_list': models.ProductImage.objects.all()})
		return context """
		
	def get_queryset(self):
		tag = self.kwargs['tag']
		self.tag = None
		if tag != 'all':
			self.tag = get_object_or_404(models.ProductTag, slug=tag)
		if self.tag:
			products = models.Product.objects.active().filter(tags=self.tag)
		else:
			products = models.Product.objects.active()
		
		return products.order_by('name')

class ProductByBrandListView(ListView):
	template_name = 'main/product_list.html'
	context_object_name = 'product_by_brand_list'
	model = models.Product
	paginate_by = 20

	def get_queryset(self):
		brand = self.kwargs['brand']
		self.brand = None
		if brand != 'all':
			self.brand = get_object_or_404(models.Brand, slug=brand)
		if self.brand:
			products = models.Product.objects.active().filter(brand=self.brand)
		else:
			products = models.Product.objects.active()
		
		return products.order_by('name')

""" class ProductSearchListView(ListView):
	template_name = 'main/product_list.html'
	context_object_name = 'product_search_list_list'
	model = models.Product
	paginate_by = 20

	def get_queryset(self):
		searchInput = self.kwargs['searchInput']
		self.searchInput = None
		if self.searchInput:
			if request.user.is_staff or request.user.is_supersuser:
				products = model.objects.filter(name=self.searchInput)
			products = models.objects.active().filter(name=self.searchInput)

		return products.order_by('name') """

class SignupView(FormView):
	template_name = 'main/auth/register.html'
	form_class = forms.UserCreationForm

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return redirect('/')
		return super().dispatch(request, *args, **kwargs)

	def get_success_url(self):
		redirect_to = self.request.GET.get('next', '/')
		return redirect_to
	
	def form_valid(self, form):
		response = super().form_valid(form)
		form.save()
		email = form.cleaned_data.get('email')
		first_name = form.cleaned_data.get('first_name')
		raw_password = form.cleaned_data.get('password1')
		logger.info('Nuevo registro para email=%s a través de SignupView', email)
		user = authenticate(email=email, password=raw_password)
		login(self.request, user)
		form.send_mail()

		return response

class AddressListView(LoginRequiredMixin, ListView):
	model = models.Address

	def get_queryset(self):
		return self.model.objects.filter(user=self.request.user)

class AddressCreateView(LoginRequiredMixin,CreateView):
	model = models.Address

	fields = ['name', 'address1', 'phone', 'zip_code', 'city', 'country']

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.user = self.request.user
		obj.save()
		return super().form_valid(form)

class AddressUpdateView(LoginRequiredMixin,UpdateView):
	model = models.Address

	fields = ['name', 'address1', 'phone', 'zip_code', 'city', 'country']

	success_url = reverse_lazy('main:address_list')

	def get_queryset(self):
		return self.model.objects.filter(user=self.request.user)

class AddressDeleteView(LoginRequiredMixin,DeleteView):
	model = models.Address
	success_url = reverse_lazy('main:address_list')

	def get_queryset(self):
		return self.model.objects.filter(user=self.request.user)

def add_basket(request):
	product = get_object_or_404(models.Product, pk=request.GET.get('product_id'))

	basket = request.basket
	if not request.basket:
		if request.user.is_authenticated:
			user = request.user
		else:
			user = None
		basket = models.Basket.objects.create(user=user)
		request.session['basket_id'] = basket.id
	
	basketline, created = models.BasketLine.objects.get_or_create(basket=basket, product=product)

	if not created:
		basketline.quantity += 1
		basketline.save()
	
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def manage_basket(request):
	if not request.basket:
		return render(request, 'basket.html', {'formset': None})

	if request.method == 'POST':
		formset = forms.BasketLineFormSet(request.POST, instance=request.basket)
		if formset.is_valid():
			formset.save()
	
	else:
		formset = forms.BasketLineFormSet(instance=request.basket)
	
	if request.basket.is_empty():
		return render(request, 'basket.html', {'formset': None})

	return render(request, 'basket.html', {'formset': formset})
	





	


		
	

main/templates/about_us.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>About Us</h1>

{% endblock content %}

main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <link rel="stylesheet" href={% static 'css/sanitize.css' %}>
    <link rel="stylesheet" href={% static 'css/contact.css' %}>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700|Open+Sans:800|Open+Sans+Condensed:300" rel="stylesheet">
    <script src="https://kit.fontawesome.com/80595e4515.js" crossorigin="anonymous"></script>
   <link rel="shortcut icon" href={% static 'images/favicon.ico' %} type="image/x-icon">
   <title>{% block title %} LDD | Relojes de Lujo {% endblock title %}</title>
</head>

<body>
    <header>
        <div class="search-scart">
           <div class="search">
           <form action="{% comment %} {% url 'main:product-search' searchInput %} {% endcomment %}" method="get">
                    <i class="fas fa-search cart"></i>
                    <input class="search-input" type="text" value="" name="searchInput" placeholder="Buscar">
                </form>
           </div>
            <div class="cart-plus-login">
                <div class="scart">
                    <a href="{% url 'main:basket' %}"><i class="fas fa-shopping-cart fa-lg"></i></a>
                    {% if request.basket %}
                        <span class="badge">{{ request.basket.count }}</span>
                    {% else %}
                        <span class="badge">0</span> 
                    {% endif %}
                </div>
                <div class="ingreso">
                    <ul class="nav nav-tabs">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{ user.first_name }}</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'main:logout' %}">Salir</a>
                                    <a class="dropdown-item" href="#">Perfil</a>
                                </div>
                            </li>
                        {% else %}  
                            <li><a href="{% url 'main:login' %}">Ingresar</a></li>  
                        {% endif %}                                                        
                   
                            {% comment %} <li class="avatar-container"> <a><img src=""></a> </li> {% endcomment %}
                        
                    </ul>
                </div>
            </div>
        </div>
        <hr style="border:0.2px solid #ccc; width: 80%;">
        <div class="logo-container">
            <a href={% url 'main:index' %}><img src={% static 'images/logo.png' %} alt="logo"></a>
            <h4>RELOJES DE LUJO</h4>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Marca</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#BrandToggler" aria-controls="BrandToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="BrandToggler">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    {% for brand in brands %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:product-brand' brand.slug %}">{{ brand.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </nav>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Tipo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#TypeToggler" aria-controls="TypeToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="TypeToggler">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    {% for tag in tags %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:products' tag.slug %}">{{ tag.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </nav>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Género</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#GenderToggler" aria-controls="GenderToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="GenderToggler">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="active"><a href="{% url 'main:products' 'hombre' %}">Hombre</a></li>
                    <li><a href="{% url 'main:products' 'mujer' %}">Mujer</a></li>
                </ul>
            </div>
        </nav>

        <nav id="MainNavOuter">
            <span>Marca</span>
            <ul id="MainNav">
                {% for brand in brands %}
                <li><a href="{% url 'main:product-brand' brand.slug %}">{{ brand.name }}</a></li>
                {% endfor %}
                <li class="last"><a href="{% url 'main:product-brand' 'all' %}">Todos</a></li>
            </ul>
        </nav>

        <nav id="SubNavOuter">
            <span>Tipo</span>
            <ul id="SubNav">
                {% for tag in tags %}
                <li><a href="{% url 'main:products' tag.slug %}">{{ tag.name }}</a></li>
                {% endfor %}
                <li class="last"><a href="{% url 'main:products' 'all' %}">Todos</a></li>
            </ul>
        </nav>

        <nav id="GenderOuter">
            <span>Género</span>
            <ul id="Gender">
                <li class="active"><a href="{% url 'main:products' 'hombre' %}">Hombre</a></li>
                <li><a href="{% url 'main:products' 'mujer' %}">Mujer</a></li>
            </ul>
        </nav>
    </header>

    {% block content %}
    {% endblock content %}

    <footer>
        <div class="f-container">
            <div class="primera-fila">
                <div class="foot-newsletter">
                    <h6>Lista de Correo</h6>
                    <form class="newsletter">
                        <div class="input-wrap">
                            <input type="text" placeholder="Ingresa tu email" name="email">
                            <button type="submit">Suscribirse</button>
                        </div>
                    </form>
                    <p style="margin-bottom: 0;">Recibe novedades y ofertas especiales</p>
                    <p id="users"></p>
                </div>

                <div class="foot-contacto">
                    <h6>Contacto</h6>
                    <address>
                        Lima 1111, CABA 1043
                    </address>
                    <a style="display: block" href="tel:+54 11 4248 7979">+54 11 4248 7979</a>
                    <a href="mailto:info@nyd.com">info@ldd.com</a>
                </div>
            </div>

            <div class="segunda-fila">
                <div class="foot-info">
                    <h6>Información</h6>
                    <ul>
                        <li><a href="{% url 'main:index' %}">Inicio</a></li>
                        <li><a href="{% url 'main:about-us' %}">Acerca de</a></li>
                        <li><a href="{% url 'main:contact' %}">Contacto</a></li>
                        <li><a href="{% url 'main:faq' %}">FAQ</a></li>
                    </ul>
                </div>

                <div class="foot-social">
                    <h6>Seguinos</h6>
                    <ul>
                        <li id="instagram"><a href="#"><i class="fab fa-instagram fa-lg"></i> Instagram</a></li>
                        <li id="facebook"><a href="#"><i class="fab fa-facebook fa-lg"></i> Facebook</a></li>
                        <li id="pinterest"><a href="#"><i class="fab fa-pinterest fa-lg"></i> Pinterest</a></li>
                        <li id="twitter"><a href="#"><i class="fab fa-twitter fa-lg"></i> Twitter</a></li>
                    </ul>
                </div>
            </div>
            <p class="copyright">Copyright 2018 - LDD</p>
        </div>
    </footer>

    <script src={% static 'js/jquery.min.js' %}></script>
    <script src={% static 'js/popper.min.js' %}></script>
    <script src={% static 'js/bootstrap.min.js' %}></script>
    <script src={% static 'js/site.js' %}></script>


</body>
</html>

main/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
            <li data-target="#carousel" data-slide-to="3"></li>
        </ol>

        <div class="carousel-inner">
            <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'images/Showcase/rolex-hero-april-desktop.jpg' %}" alt="First slide">                
            </div>
            <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/Showcase/hublot-world-cup-desktop.jpg' %}" alt="Second slide">
            </div>
            <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/Showcase/cartiersantos-desktop.jpg' %}" alt="Third slide">
            </div>
            <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'images/Showcase/tag-comp-hp-hero.jpg' %}" alt="Third slide">
            </div>
            
        </div>
        <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="about">
            <h3>Lorem ipsum, dolor sit amet consectetur adipisicing elit.</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi impedit saepe nihil ea, eligendi exercitationem
                ipsum quia, quibusdam et porro distinctio enim vero consectetur incidunt vel aliquam autem, nam sapiente.
            </p>
            <a class="boton-tr" href="{% url 'main:register' %}">Registrarse</a>
    </div>
    <section>
        <div class="second-sponsor">
            <div class="sp-description">
                <div class="sp-text">
                    <a href="#">Profesional</a>
                    <p> Uno de los lemas más antiguos de Breitling es "Instrumentos para profesionales". Esas palabras están vigentes hoy más que nunca.
                        Los relojes de la "Colección Profesional" están equipados con las características necesarias para ser los socios perfectos
                        de los aventurero.
                        </p>
                    <a class="sp-button" href="#" class="button outline">Descubre la colección</a>
                </div>
                <div class="sp-img">
                    <a href="#" title="Breitling-clock">
                        <img src="{% static 'images/breitling-home.png' %}" alt="Professional">
                    </a>
                </div>
            </div>
        </div>
    </section>
    <div class="brands">
        <ul>
            {% for brand in brands %}
                <li>
                    <a href="{% url 'main:product-brand' brand.slug %}">
                        <img src="{{ brand.logo.url }}" alt="logo">
                    </a>
                </li>
            {% endfor %}  
        </ul>
        <a class="boton-tr" href="#">todas las marcas</a>
    </div>
    <hr style="border:0.2px solid #ccc; width: 80%; margin: 0 auto;">
    <div class="destacados">
        <h3>Colección 2020</h3>
        <div class="collections">
            <img class="foto" src="{% static 'images/collections/cartier-brand.jpg' %}">
            <img class="logo" src="{% static 'images/collections/cartier.png' %}">
            <a class="boton-tr" href="#">Ver colección</a>
        </div>
        <div class="collections">
            <img class="foto" src="{% static 'images/collections/brand-hublot.jpg' %}">
            <img class="logo" src="{% static 'images/collections/hublot.png' %}">
            <a class="boton-tr" href="#">Ver colección</a>
        </div>
        <div class="collections">
            <img class="foto" src="{% static 'images/collections/iwc-image.jpg' %}">
            <img class="logo" src="{% static 'images/collections/iwc.png' %}">
            <a class="boton-tr" href="#">Ver colección</a>
        </div>
        <div class="collections">
            <img class="foto" src="{% static 'images/collections/omega-brand.jpg' %}">
            <img class="logo" src="{% static 'images/collections/omega.png' %}">
            <a class="boton-tr" href="#">Ver colección</a>
        </div>
    </div>
</main>

{% endblock content %}